//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class ConfigToolModbusResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/ConfigToolModbus";
        public override string RosMessageName => k_RosMessageName;

        public string message;
        public short ret;

        public ConfigToolModbusResponse()
        {
            this.message = "";
            this.ret = 0;
        }

        public ConfigToolModbusResponse(string message, short ret)
        {
            this.message = message;
            this.ret = ret;
        }

        public static ConfigToolModbusResponse Deserialize(MessageDeserializer deserializer) => new ConfigToolModbusResponse(deserializer);

        private ConfigToolModbusResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.message);
            deserializer.Read(out this.ret);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.message);
            serializer.Write(this.ret);
        }

        public override string ToString()
        {
            return "ConfigToolModbusResponse: " +
            "\nmessage: " + message.ToString() +
            "\nret: " + ret.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
