//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetAnalogIOResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetAnalogIO";
        public override string RosMessageName => k_RosMessageName;

        public float analog_value;
        public short ret;
        public string message;

        public GetAnalogIOResponse()
        {
            this.analog_value = 0.0f;
            this.ret = 0;
            this.message = "";
        }

        public GetAnalogIOResponse(float analog_value, short ret, string message)
        {
            this.analog_value = analog_value;
            this.ret = ret;
            this.message = message;
        }

        public static GetAnalogIOResponse Deserialize(MessageDeserializer deserializer) => new GetAnalogIOResponse(deserializer);

        private GetAnalogIOResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.analog_value);
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.analog_value);
            serializer.Write(this.ret);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "GetAnalogIOResponse: " +
            "\nanalog_value: " + analog_value.ToString() +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
