//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetControllerDigitalIOResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetControllerDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        public short ret;
        public short value;
        public string message;

        public GetControllerDigitalIOResponse()
        {
            this.ret = 0;
            this.value = 0;
            this.message = "";
        }

        public GetControllerDigitalIOResponse(short ret, short value, string message)
        {
            this.ret = ret;
            this.value = value;
            this.message = message;
        }

        public static GetControllerDigitalIOResponse Deserialize(MessageDeserializer deserializer) => new GetControllerDigitalIOResponse(deserializer);

        private GetControllerDigitalIOResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.value);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.value);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "GetControllerDigitalIOResponse: " +
            "\nret: " + ret.ToString() +
            "\nvalue: " + value.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
