//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetDigitalIOResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        public int digital_1;
        public int digital_2;
        public short ret;
        public string message;

        public GetDigitalIOResponse()
        {
            this.digital_1 = 0;
            this.digital_2 = 0;
            this.ret = 0;
            this.message = "";
        }

        public GetDigitalIOResponse(int digital_1, int digital_2, short ret, string message)
        {
            this.digital_1 = digital_1;
            this.digital_2 = digital_2;
            this.ret = ret;
            this.message = message;
        }

        public static GetDigitalIOResponse Deserialize(MessageDeserializer deserializer) => new GetDigitalIOResponse(deserializer);

        private GetDigitalIOResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.digital_1);
            deserializer.Read(out this.digital_2);
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.digital_1);
            serializer.Write(this.digital_2);
            serializer.Write(this.ret);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "GetDigitalIOResponse: " +
            "\ndigital_1: " + digital_1.ToString() +
            "\ndigital_2: " + digital_2.ToString() +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
