//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GripperStateResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GripperState";
        public override string RosMessageName => k_RosMessageName;

        public float curr_pos;
        public short err_code;

        public GripperStateResponse()
        {
            this.curr_pos = 0.0f;
            this.err_code = 0;
        }

        public GripperStateResponse(float curr_pos, short err_code)
        {
            this.curr_pos = curr_pos;
            this.err_code = err_code;
        }

        public static GripperStateResponse Deserialize(MessageDeserializer deserializer) => new GripperStateResponse(deserializer);

        private GripperStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.curr_pos);
            deserializer.Read(out this.err_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.curr_pos);
            serializer.Write(this.err_code);
        }

        public override string ToString()
        {
            return "GripperStateResponse: " +
            "\ncurr_pos: " + curr_pos.ToString() +
            "\nerr_code: " + err_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
