//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GripperConfigRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GripperConfig";
        public override string RosMessageName => k_RosMessageName;

        //  Grip velocity configuration: range is from 1 to 5000
        public float pulse_vel;

        public GripperConfigRequest()
        {
            this.pulse_vel = 0.0f;
        }

        public GripperConfigRequest(float pulse_vel)
        {
            this.pulse_vel = pulse_vel;
        }

        public static GripperConfigRequest Deserialize(MessageDeserializer deserializer) => new GripperConfigRequest(deserializer);

        private GripperConfigRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pulse_vel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pulse_vel);
        }

        public override string ToString()
        {
            return "GripperConfigRequest: " +
            "\npulse_vel: " + pulse_vel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
