//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetDigitalIORequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        //  Setting the 2 digital Output port at robot end connector
        public short io_num;
        public short value;

        public SetDigitalIORequest()
        {
            this.io_num = 0;
            this.value = 0;
        }

        public SetDigitalIORequest(short io_num, short value)
        {
            this.io_num = io_num;
            this.value = value;
        }

        public static SetDigitalIORequest Deserialize(MessageDeserializer deserializer) => new SetDigitalIORequest(deserializer);

        private SetDigitalIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.io_num);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.io_num);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetDigitalIORequest: " +
            "\nio_num: " + io_num.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
