//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetInt16Request : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetInt16";
        public override string RosMessageName => k_RosMessageName;

        //  request: set robot state or mode.
        //  data: int value indicating command robot state or execution mode.
        public short data;

        public SetInt16Request()
        {
            this.data = 0;
        }

        public SetInt16Request(short data)
        {
            this.data = data;
        }

        public static SetInt16Request Deserialize(MessageDeserializer deserializer) => new SetInt16Request(deserializer);

        private SetInt16Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SetInt16Request: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
