//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetLoadResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetLoad";
        public override string RosMessageName => k_RosMessageName;

        public short ret;
        public string message;

        public SetLoadResponse()
        {
            this.ret = 0;
            this.message = "";
        }

        public SetLoadResponse(short ret, string message)
        {
            this.ret = ret;
            this.message = message;
        }

        public static SetLoadResponse Deserialize(MessageDeserializer deserializer) => new SetLoadResponse(deserializer);

        private SetLoadResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SetLoadResponse: " +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
