//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetLoadRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetLoad";
        public override string RosMessageName => k_RosMessageName;

        //  to set robot load parameters, based on initial Tool Frame located at flange center.
        //  Load mass (kg)
        public float mass;
        //  Load Center of Mass (mm), with respect to intial Tool Frame
        public float xc;
        public float yc;
        public float zc;

        public SetLoadRequest()
        {
            this.mass = 0.0f;
            this.xc = 0.0f;
            this.yc = 0.0f;
            this.zc = 0.0f;
        }

        public SetLoadRequest(float mass, float xc, float yc, float zc)
        {
            this.mass = mass;
            this.xc = xc;
            this.yc = yc;
            this.zc = zc;
        }

        public static SetLoadRequest Deserialize(MessageDeserializer deserializer) => new SetLoadRequest(deserializer);

        private SetLoadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mass);
            deserializer.Read(out this.xc);
            deserializer.Read(out this.yc);
            deserializer.Read(out this.zc);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mass);
            serializer.Write(this.xc);
            serializer.Write(this.yc);
            serializer.Write(this.zc);
        }

        public override string ToString()
        {
            return "SetLoadRequest: " +
            "\nmass: " + mass.ToString() +
            "\nxc: " + xc.ToString() +
            "\nyc: " + yc.ToString() +
            "\nzc: " + zc.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
