//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetToolModbusRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetToolModbus";
        public override string RosMessageName => k_RosMessageName;

        //  unsigned char data to be sent to tool device through modbus
        public byte[] send_data;
        //  Specify the anticipated maximum respond data length in bytes
        public short respond_len;

        public SetToolModbusRequest()
        {
            this.send_data = new byte[0];
            this.respond_len = 0;
        }

        public SetToolModbusRequest(byte[] send_data, short respond_len)
        {
            this.send_data = send_data;
            this.respond_len = respond_len;
        }

        public static SetToolModbusRequest Deserialize(MessageDeserializer deserializer) => new SetToolModbusRequest(deserializer);

        private SetToolModbusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.send_data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.respond_len);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.send_data);
            serializer.Write(this.send_data);
            serializer.Write(this.respond_len);
        }

        public override string ToString()
        {
            return "SetToolModbusRequest: " +
            "\nsend_data: " + System.String.Join(", ", send_data.ToList()) +
            "\nrespond_len: " + respond_len.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
