//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class TCPOffsetRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/TCPOffset";
        public override string RosMessageName => k_RosMessageName;

        //  to give robot floating point number Cartesian TCP offset, based on initial Tool Frame located at flange center.
        public float x;
        public float y;
        public float z;
        public float roll;
        public float pitch;
        public float yaw;

        public TCPOffsetRequest()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.roll = 0.0f;
            this.pitch = 0.0f;
            this.yaw = 0.0f;
        }

        public TCPOffsetRequest(float x, float y, float z, float roll, float pitch, float yaw)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
        }

        public static TCPOffsetRequest Deserialize(MessageDeserializer deserializer) => new TCPOffsetRequest(deserializer);

        private TCPOffsetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
        }

        public override string ToString()
        {
            return "TCPOffsetRequest: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
