//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixXs
{
    [Serializable]
    public class OperatingModesResponse : Message
    {
        public const string k_RosMessageName = "interbotix_xs_msgs/OperatingModes";
        public override string RosMessageName => k_RosMessageName;


        public OperatingModesResponse()
        {
        }
        public static OperatingModesResponse Deserialize(MessageDeserializer deserializer) => new OperatingModesResponse(deserializer);

        private OperatingModesResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "OperatingModesResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
