//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixXs
{
    [Serializable]
    public class RebootRequest : Message
    {
        public const string k_RosMessageName = "interbotix_xs_msgs/Reboot";
        public override string RosMessageName => k_RosMessageName;

        //  Reboot motors
        // 
        //  Note that if a dual-joint is selected, both motors will be rebooted. Also note
        //  that motors will NOT hold position during the reboot process. Additionally, only
        //  EEPROM registers will retain their values, but RAM registers will not. See details
        //  at https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/#area-eeprom-ram
        public string cmd_type;
        //  set to 'group' if commanding a joint group or 'single' if commanding a single joint
        public string name;
        //  name of the group if commanding a joint group or joint if commanding a single joint
        public bool enable;
        //  whether to torque the selected joints on after reboot
        public bool smart_reboot;
        //  set to true to only reboot motors in a specified group that are in an error state
        //  (as opposed to a blanket reboot of all motors in said group)

        public RebootRequest()
        {
            this.cmd_type = "";
            this.name = "";
            this.enable = false;
            this.smart_reboot = false;
        }

        public RebootRequest(string cmd_type, string name, bool enable, bool smart_reboot)
        {
            this.cmd_type = cmd_type;
            this.name = name;
            this.enable = enable;
            this.smart_reboot = smart_reboot;
        }

        public static RebootRequest Deserialize(MessageDeserializer deserializer) => new RebootRequest(deserializer);

        private RebootRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.name);
            deserializer.Read(out this.enable);
            deserializer.Read(out this.smart_reboot);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_type);
            serializer.Write(this.name);
            serializer.Write(this.enable);
            serializer.Write(this.smart_reboot);
        }

        public override string ToString()
        {
            return "RebootRequest: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\nname: " + name.ToString() +
            "\nenable: " + enable.ToString() +
            "\nsmart_reboot: " + smart_reboot.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
