//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixXs
{
    [Serializable]
    public class RegisterValuesResponse : Message
    {
        public const string k_RosMessageName = "interbotix_xs_msgs/RegisterValues";
        public override string RosMessageName => k_RosMessageName;

        public int[] values;
        //  current register values (only filled if 'getting' a register)

        public RegisterValuesResponse()
        {
            this.values = new int[0];
        }

        public RegisterValuesResponse(int[] values)
        {
            this.values = values;
        }

        public static RegisterValuesResponse Deserialize(MessageDeserializer deserializer) => new RegisterValuesResponse(deserializer);

        private RegisterValuesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.values, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "RegisterValuesResponse: " +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
