//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixXs
{
    [Serializable]
    public class ArmJoyMsg : Message
    {
        public const string k_RosMessageName = "interbotix_xs_msgs/ArmJoy";
        public override string RosMessageName => k_RosMessageName;

        //  This message is used specifically in the interbotix_xsarm_joy package
        // 
        //  Maps raw 'joy' commands to more specific ones to control an Interbotix manipulator
        //  enum values that define the joystick controls for the robot
        // ########################################################################################################
        //  Control the motion of the virtual 'ee_gripper_link' or end effector using the modern_robotics_ik engine
        //  Position Control
        public const sbyte EE_X_INC = 1;
        public const sbyte EE_X_DEC = 2;
        public const sbyte EE_Y_INC = 3;
        public const sbyte EE_Y_DEC = 4;
        public const sbyte EE_Z_INC = 5;
        public const sbyte EE_Z_DEC = 6;
        //  Orientation Control
        public const sbyte EE_ROLL_CCW = 7;
        public const sbyte EE_ROLL_CW = 8;
        public const sbyte EE_PITCH_UP = 9;
        public const sbyte EE_PITCH_DOWN = 10;
        // ########################################################################################################
        //  Control the motion of independent joints on the Arm or send predefined robot poses
        //  Waist Joint Control
        public const sbyte WAIST_CCW = 11;
        public const sbyte WAIST_CW = 12;
        //  Gripper Control
        public const sbyte GRIPPER_OPEN = 13;
        public const sbyte GRIPPER_CLOSE = 14;
        //  Pose Control
        public const sbyte HOME_POSE = 15;
        public const sbyte SLEEP_POSE = 16;
        // ########################################################################################################
        //  Customize configurations for the Interbotix Arm
        //  Inc/Dec Joint speed
        public const sbyte SPEED_INC = 17;
        public const sbyte SPEED_DEC = 18;
        //  Quickly toggle between a fast and slow speed setting
        public const sbyte SPEED_COURSE = 19;
        public const sbyte SPEED_FINE = 20;
        //  Inc/Dec Gripper pressure
        public const sbyte GRIPPER_PWM_INC = 21;
        public const sbyte GRIPPER_PWM_DEC = 22;
        //  Torque On/Off all servos
        public const sbyte TORQUE_ON = 23;
        public const sbyte TORQUE_OFF = 24;
        // ########################################################################################################
        //  Control the motion of the Interbotix Arm
        public sbyte ee_x_cmd;
        public sbyte ee_y_cmd;
        public sbyte ee_z_cmd;
        public sbyte ee_roll_cmd;
        public sbyte ee_pitch_cmd;
        //  Independent Joint/Pose Control
        public sbyte waist_cmd;
        public sbyte gripper_cmd;
        public sbyte pose_cmd;
        //  Misc. Configs
        public sbyte speed_cmd;
        public sbyte speed_toggle_cmd;
        public sbyte gripper_pwm_cmd;
        public sbyte torque_cmd;

        public ArmJoyMsg()
        {
            this.ee_x_cmd = 0;
            this.ee_y_cmd = 0;
            this.ee_z_cmd = 0;
            this.ee_roll_cmd = 0;
            this.ee_pitch_cmd = 0;
            this.waist_cmd = 0;
            this.gripper_cmd = 0;
            this.pose_cmd = 0;
            this.speed_cmd = 0;
            this.speed_toggle_cmd = 0;
            this.gripper_pwm_cmd = 0;
            this.torque_cmd = 0;
        }

        public ArmJoyMsg(sbyte ee_x_cmd, sbyte ee_y_cmd, sbyte ee_z_cmd, sbyte ee_roll_cmd, sbyte ee_pitch_cmd, sbyte waist_cmd, sbyte gripper_cmd, sbyte pose_cmd, sbyte speed_cmd, sbyte speed_toggle_cmd, sbyte gripper_pwm_cmd, sbyte torque_cmd)
        {
            this.ee_x_cmd = ee_x_cmd;
            this.ee_y_cmd = ee_y_cmd;
            this.ee_z_cmd = ee_z_cmd;
            this.ee_roll_cmd = ee_roll_cmd;
            this.ee_pitch_cmd = ee_pitch_cmd;
            this.waist_cmd = waist_cmd;
            this.gripper_cmd = gripper_cmd;
            this.pose_cmd = pose_cmd;
            this.speed_cmd = speed_cmd;
            this.speed_toggle_cmd = speed_toggle_cmd;
            this.gripper_pwm_cmd = gripper_pwm_cmd;
            this.torque_cmd = torque_cmd;
        }

        public static ArmJoyMsg Deserialize(MessageDeserializer deserializer) => new ArmJoyMsg(deserializer);

        private ArmJoyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ee_x_cmd);
            deserializer.Read(out this.ee_y_cmd);
            deserializer.Read(out this.ee_z_cmd);
            deserializer.Read(out this.ee_roll_cmd);
            deserializer.Read(out this.ee_pitch_cmd);
            deserializer.Read(out this.waist_cmd);
            deserializer.Read(out this.gripper_cmd);
            deserializer.Read(out this.pose_cmd);
            deserializer.Read(out this.speed_cmd);
            deserializer.Read(out this.speed_toggle_cmd);
            deserializer.Read(out this.gripper_pwm_cmd);
            deserializer.Read(out this.torque_cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ee_x_cmd);
            serializer.Write(this.ee_y_cmd);
            serializer.Write(this.ee_z_cmd);
            serializer.Write(this.ee_roll_cmd);
            serializer.Write(this.ee_pitch_cmd);
            serializer.Write(this.waist_cmd);
            serializer.Write(this.gripper_cmd);
            serializer.Write(this.pose_cmd);
            serializer.Write(this.speed_cmd);
            serializer.Write(this.speed_toggle_cmd);
            serializer.Write(this.gripper_pwm_cmd);
            serializer.Write(this.torque_cmd);
        }

        public override string ToString()
        {
            return "ArmJoyMsg: " +
            "\nee_x_cmd: " + ee_x_cmd.ToString() +
            "\nee_y_cmd: " + ee_y_cmd.ToString() +
            "\nee_z_cmd: " + ee_z_cmd.ToString() +
            "\nee_roll_cmd: " + ee_roll_cmd.ToString() +
            "\nee_pitch_cmd: " + ee_pitch_cmd.ToString() +
            "\nwaist_cmd: " + waist_cmd.ToString() +
            "\ngripper_cmd: " + gripper_cmd.ToString() +
            "\npose_cmd: " + pose_cmd.ToString() +
            "\nspeed_cmd: " + speed_cmd.ToString() +
            "\nspeed_toggle_cmd: " + speed_toggle_cmd.ToString() +
            "\ngripper_pwm_cmd: " + gripper_pwm_cmd.ToString() +
            "\ntorque_cmd: " + torque_cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
