//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.InterbotixXs
{
    [Serializable]
    public class JointTempsMsg : Message
    {
        public const string k_RosMessageName = "interbotix_xs_msgs/JointTemps";
        public override string RosMessageName => k_RosMessageName;

        //  This message is used specifically in the interbotix_xsarm_diagnostic_tool package
        //  Holds the temperatures [C] for the specified joints
        public string[] names;
        public int[] temps;

        public JointTempsMsg()
        {
            this.names = new string[0];
            this.temps = new int[0];
        }

        public JointTempsMsg(string[] names, int[] temps)
        {
            this.names = names;
            this.temps = temps;
        }

        public static JointTempsMsg Deserialize(MessageDeserializer deserializer) => new JointTempsMsg(deserializer);

        private JointTempsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.temps, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.temps);
            serializer.Write(this.temps);
        }

        public override string ToString()
        {
            return "JointTempsMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\ntemps: " + System.String.Join(", ", temps.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
