//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetAnalogIORequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetAnalogIO";
        public override string RosMessageName => k_RosMessageName;

        //  Getting one of the 2 analog Input port at robot end connector
        public short port_num;

        public GetAnalogIORequest()
        {
            this.port_num = 0;
        }

        public GetAnalogIORequest(short port_num)
        {
            this.port_num = port_num;
        }

        public static GetAnalogIORequest Deserialize(MessageDeserializer deserializer) => new GetAnalogIORequest(deserializer);

        private GetAnalogIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.port_num);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.port_num);
        }

        public override string ToString()
        {
            return "GetAnalogIORequest: " +
            "\nport_num: " + port_num.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
