//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetControllerDigitalIORequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetControllerDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        //  Getting the controller DIGITAL input port status, io_num: from 1 to 8
        public short io_num;

        public GetControllerDigitalIORequest()
        {
            this.io_num = 0;
        }

        public GetControllerDigitalIORequest(short io_num)
        {
            this.io_num = io_num;
        }

        public static GetControllerDigitalIORequest Deserialize(MessageDeserializer deserializer) => new GetControllerDigitalIORequest(deserializer);

        private GetControllerDigitalIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.io_num);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.io_num);
        }

        public override string ToString()
        {
            return "GetControllerDigitalIORequest: " +
            "\nio_num: " + io_num.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
