//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetDigitalIORequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        //  Getting the 2 digital Input port at robot end connector

        public GetDigitalIORequest()
        {
        }
        public static GetDigitalIORequest Deserialize(MessageDeserializer deserializer) => new GetDigitalIORequest(deserializer);

        private GetDigitalIORequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetDigitalIORequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
