//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GripperMoveRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GripperMove";
        public override string RosMessageName => k_RosMessageName;

        //  position command of gripper: range from 0(close) to 850 (open)
        public float pulse_pos;

        public GripperMoveRequest()
        {
            this.pulse_pos = 0.0f;
        }

        public GripperMoveRequest(float pulse_pos)
        {
            this.pulse_pos = pulse_pos;
        }

        public static GripperMoveRequest Deserialize(MessageDeserializer deserializer) => new GripperMoveRequest(deserializer);

        private GripperMoveRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pulse_pos);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pulse_pos);
        }

        public override string ToString()
        {
            return "GripperMoveRequest: " +
            "\npulse_pos: " + pulse_pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
