//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetAxisResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetAxis";
        public override string RosMessageName => k_RosMessageName;

        //  response: 
        // 	ret is 0 for successful execution and others for errors or warnings occured
        // 	message is a string returned by function, indicating execution status.
        public short ret;
        public string message;

        public SetAxisResponse()
        {
            this.ret = 0;
            this.message = "";
        }

        public SetAxisResponse(short ret, string message)
        {
            this.ret = ret;
            this.message = message;
        }

        public static SetAxisResponse Deserialize(MessageDeserializer deserializer) => new SetAxisResponse(deserializer);

        private SetAxisResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SetAxisResponse: " +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
