//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TelecobotRosUnity
{
    [Serializable]
    public class TelecobotArmControlMsg : Message
    {
        public const string k_RosMessageName = "telecobot_ros_unity/TelecobotArmControl";
        public override string RosMessageName => k_RosMessageName;

        public int arm_control_mode;
        public Geometry.PoseMsg end_effector_pose;
        public Geometry.PoseMsg goal_pose;

        public TelecobotArmControlMsg()
        {
            this.arm_control_mode = 0;
            this.end_effector_pose = new Geometry.PoseMsg();
            this.goal_pose = new Geometry.PoseMsg();
        }

        public TelecobotArmControlMsg(int arm_control_mode, double[] joints, Geometry.PoseMsg end_effector_pose, Geometry.PoseMsg goal_pose)
        {
            this.arm_control_mode = arm_control_mode;
            this.end_effector_pose = end_effector_pose;
            this.goal_pose = goal_pose;
        }

        public static TelecobotArmControlMsg Deserialize(MessageDeserializer deserializer) => new TelecobotArmControlMsg(deserializer);

        private TelecobotArmControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.arm_control_mode);
            this.end_effector_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.goal_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.arm_control_mode);
            serializer.Write(this.end_effector_pose);
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "TelecobotArmControlMsg: " +
            "\narm_control_mode: " + arm_control_mode.ToString() +
            "\nend_effector_pose: " + end_effector_pose.ToString() +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
