//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Telecobot_ros_unity
{
    [Serializable]
    public class TelecobotBaseControlMsg : Message
    {
        public const string k_RosMessageName = "telecobot_ros_unity/TelecobotBaseControl";
        public override string RosMessageName => k_RosMessageName;

        public int base_control_mode;
        public Geometry.PoseMsg goal;

        public TelecobotBaseControlMsg()
        {
            this.base_control_mode = 0;
            this.goal = new Geometry.PoseMsg();
        }

        public TelecobotBaseControlMsg(int base_control_mode, Geometry.PoseMsg goal)
        {
            this.base_control_mode = base_control_mode;
            this.goal = goal;
        }

        public static TelecobotBaseControlMsg Deserialize(MessageDeserializer deserializer) => new TelecobotBaseControlMsg(deserializer);

        private TelecobotBaseControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.base_control_mode);
            this.goal = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.base_control_mode);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "TelecobotBaseControlMsg: " +
            "\nbase_control_mode: " + base_control_mode.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
