//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Telecobot_ros_unity
{
    [Serializable]
    public class TelecobotMoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "telecobot_ros_unity/TelecobotMoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg goal_pose;

        public TelecobotMoveitJointsMsg()
        {
            this.joints = new double[5];
            this.goal_pose = new Geometry.PoseMsg();
        }

        public TelecobotMoveitJointsMsg(double[] joints, Geometry.PoseMsg goal_pose)
        {
            this.joints = joints;
            this.goal_pose = goal_pose;
        }

        public static TelecobotMoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new TelecobotMoveitJointsMsg(deserializer);

        private TelecobotMoveitJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 5);
            this.goal_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "TelecobotMoveitJointsMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
